### ISSUE TITLE
Unable to install csharp plugin

### ISSUE THREAD

**Issue by rkumarrb** [getgauge/gauge-tests#13]
In the latest version 0.6.0. Unable to install csharp language plugin. It shows error that there is no compatible csharp plugin.

**Comment by mahendrakariya** [comment]
@rkumarrb We haven't yet released the C# plugin for Gauge 0.6.0. We will be releasing it in a couple of days, once the testing is complete.

**Comment by rkumarrb** [comment]
@mahendrakariya - Oh great. Thank you for letting me know. I will try again by next week. Till that will play around with Java

**Comment by mahendrakariya** [comment]
@rkumarrb We have released the C# plugin for Gauge 0.6.0. Please run `gauge --install csharp`.

**Comment by rkumarrb** [comment]
Thank you for letting me know. I tried today morning and still playing around. will keep in touch. Thanks
